### ISSUE TITLE
Evernote::EDAM::Error::EDAMUserException on findNotes --- with full access key

### ISSUE THREAD

**Issue by ricsrock** [Evernote/evernote-oauth-ruby#22]
I requested full access for my API key and got an email response from Evernote that it had been granted.

I can successfully do this:

```
 client.note_store.listNotebooks
```

and get a list of notebooks.

But when I do this:

```
 client.note_store.findNotes(Evernote::EDAM::NoteStore::NoteFilter.new, 0, 10).first.tags.first.parent
```

I get this:

```
 Evernote::EDAM::Error::EDAMUserException: Evernote::EDAM::Error::EDAMUserException
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/note_store.rb:450:in `recv_findNotes'
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/evernote-thrift-1.25.1/lib/Evernote/EDAM/note_store.rb:440:in `findNotes'
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/evernote_oauth-0.2.3/lib/evernote_oauth/thrift_client_delegation.rb:11:in `method_missing'
from (irb):70
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in `start'
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
from /Users/lkenyan/.rvm/gems/ruby-2.0.0-p247@revolution_gemset/gems/railties-4.0.0/lib/rails/commands.rb:64:in `<top (required)>'
from bin/rails:4:in `require'
from bin/rails:4:in `<main>'
```

And help is appreciated! Thanks.

**Comment by ndw** [comment]
Shame no one from Evernote replied. AFAICT, this is related to rate limiting in some way. At least, my experience was that my "backup" app ran for a bit then stopped. Attempting to restart it lead to the "method missing" error you reported. Twenty or thirty minutes later, running my app again worked.
